# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_crds.argoproj as __argoproj
    argoproj = __argoproj
    import pulumi_crds.meta as __meta
    meta = __meta
    import pulumi_crds.secrets as __secrets
    secrets = __secrets
else:
    argoproj = _utilities.lazy_import('pulumi_crds.argoproj')
    meta = _utilities.lazy_import('pulumi_crds.meta')
    secrets = _utilities.lazy_import('pulumi_crds.secrets')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "crds",
  "mod": "argoproj.io/v1alpha1",
  "fqn": "pulumi_crds.argoproj.v1alpha1",
  "classes": {
   "kubernetes:argoproj.io/v1alpha1:AppProject": "AppProject",
   "kubernetes:argoproj.io/v1alpha1:AppProjectList": "AppProjectList",
   "kubernetes:argoproj.io/v1alpha1:AppProjectPatch": "AppProjectPatch",
   "kubernetes:argoproj.io/v1alpha1:Application": "Application",
   "kubernetes:argoproj.io/v1alpha1:ApplicationList": "ApplicationList",
   "kubernetes:argoproj.io/v1alpha1:ApplicationPatch": "ApplicationPatch",
   "kubernetes:argoproj.io/v1alpha1:ApplicationSet": "ApplicationSet",
   "kubernetes:argoproj.io/v1alpha1:ApplicationSetList": "ApplicationSetList",
   "kubernetes:argoproj.io/v1alpha1:ApplicationSetPatch": "ApplicationSetPatch"
  }
 },
 {
  "pkg": "crds",
  "mod": "secrets.hashicorp.com/v1beta1",
  "fqn": "pulumi_crds.secrets.v1beta1",
  "classes": {
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultAuth": "VaultAuth",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultAuthList": "VaultAuthList",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultAuthPatch": "VaultAuthPatch",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultConnection": "VaultConnection",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultConnectionList": "VaultConnectionList",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultConnectionPatch": "VaultConnectionPatch",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultDynamicSecret": "VaultDynamicSecret",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultDynamicSecretList": "VaultDynamicSecretList",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultDynamicSecretPatch": "VaultDynamicSecretPatch",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultPKISecret": "VaultPKISecret",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultPKISecretList": "VaultPKISecretList",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultPKISecretPatch": "VaultPKISecretPatch",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultStaticSecret": "VaultStaticSecret",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultStaticSecretList": "VaultStaticSecretList",
   "kubernetes:secrets.hashicorp.com/v1beta1:VaultStaticSecretPatch": "VaultStaticSecretPatch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "crds",
  "token": "pulumi:providers:kubernetes",
  "fqn": "pulumi_crds",
  "class": "Provider"
 }
]
"""
)
