apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temp-egress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/projectinitiative/homelab.git
    targetRevision: HEAD
    path: apps/base/temp-egress/config
  destination:
    server: https://kubernetes.default.svc
    # The namespace is hardcoded in the manifests, so we don't need to specify it here.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
