apiVersion: v2
name: observability
description: Observability stack (Prometheus, Thanos, Loki) backed by Garage S3
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: "61.3.2"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: loki
    version: "6.6.3"
    repository: "https://grafana.github.io/helm-charts"
