# homelab.git/bootstrap/control-cluster/helm-values/cert-manager-values.yaml
installCRDs: true # Set to true to install cert-manager's CRDs
# Other cert-manager values if needed, e.g., resource requests/limits, replicas
