apiVersion: v1
kind: ConfigMap
metadata:
  name: pulumi-cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: pulumi-python
    spec:
      version: v1.0
      init:
        command: ["/bin/sh", "-c"]
        args: ["pulumi-init"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["pulumi-generate"]
      discover:
        fileName: "Pulumi.yaml"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
      - name: pulumi-cmp
        image: ghcr.io/projectinitiative/pulumi-cmp-plugin:latest
        command: ["/var/run/argocd/argocd-cmp-server"]
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        env:
          - name: HOME
            value: /home/argocd
          - name: PULUMI_HOME
            value: /home/argocd/.pulumi
        volumeMounts:
          - name: var-files
            mountPath: /var/run/argocd
          - name: plugin-config
            mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: plugin.yaml
          - name: tmp
            mountPath: /tmp
          - name: home
            mountPath: /home/argocd
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: '1'
            memory: 1024Mi
      volumes:
      - name: plugin-config
        configMap:
          name: pulumi-cmp-plugin
      - name: tmp
        emptyDir: {}
      - name: home
        emptyDir: {}
