apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-istio-root-ca-issuer
spec:
  selfSigned: {} # This tells cert-manager to generate a self-signed CA
---
# Optional: Create a certificate for the root CA itself so you can easily get its public key
# This secret (homelab-istio-root-ca-secret) will hold your root CA's cert and key
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-istio-root-ca
  namespace: cert-manager # Or istio-system, or a dedicated namespace
spec:
  isCA: true
  commonName: homelab-istio-root-ca
  secretName: homelab-istio-root-ca-secret # cert-manager will store the CA here
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: homelab-istio-root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
