apiVersion: v1
kind: Service
metadata:
  name: argocd-server-tailscale
  namespace: argocd # Ensure this matches the namespace of your argocd-server
spec:
  selector:
    app.kubernetes.io/name: argocd-server # This is the selector from your argocd-server service
  ports:
    - name: http
      protocol: TCP
      port: 80 # The port you want to expose on Tailscale
      targetPort: 8080 # The targetPort your argocd-server pods are listening on
    - name: https
      protocol: TCP
      port: 443 # The port you want to expose on Tailscale
      targetPort: 8080 # The targetPort your argocd-server pods are listening on
  type: LoadBalancer
  loadBalancerClass: tailscale
