apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-registry
  namespace: registry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: local-registry
  template:
    metadata:
      labels:
        app: local-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: registry-s3-creds
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry/
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
      volumes:
      - name: config
        configMap:
          name: registry-config
