#!/usr/bin/env python3
"""Exercise vLLM mixed prefill/decode continuous batching.

Starts one long, predictable streaming decode (the anchor). After its first token,
submits multiple unique large prompts together. While requests run, polls vLLM's
Prometheus endpoint and prints prompt/generation token rates, scheduler state,
and KV-cache usage. An interval with both prompt_delta and generation_delta > 0
is direct evidence that prefill and decode progressed concurrently.

Only the traffic generated by this process should use the endpoint during a run;
Prometheus counters include all clients.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import re
import statistics
import sys
import threading
import time
import urllib.error
import urllib.request
import uuid
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

METRIC_RE = re.compile(r'^([^\s{]+)(?:\{([^}]*)\})?\s+([-+0-9.eE]+)$')


@dataclass
class RequestResult:
    name: str
    ok: bool
    status: int | None
    started_s: float
    ttft_s: float | None
    wall_s: float
    decode_s: float | None
    prompt_tokens: int
    completion_tokens: int
    effective_prefill_tok_s: float | None
    decode_tok_s: float | None
    delivered_completion_tok_s: float | None
    finish_reason: str | None
    error: str | None = None


def request(url: str, path: str, *, data: bytes | None = None,
            api_key: str | None = None, timeout: float = 30.0):
    headers = {"Accept": "application/json"}
    if data is not None:
        headers["Content-Type"] = "application/json"
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    return urllib.request.urlopen(
        urllib.request.Request(url.rstrip("/") + path, data=data, headers=headers),
        timeout=timeout,
    )


def metric_snapshot(url: str, api_key: str | None) -> dict[str, float]:
    with request(url, "/metrics", api_key=api_key, timeout=10.0) as response:
        text = response.read().decode("utf-8", "replace")

    values: dict[str, float] = {}
    deferred = 0.0
    capacity = 0.0
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        match = METRIC_RE.match(line)
        if not match:
            continue
        name, labels, raw = match.groups()
        value = float(raw)
        values[name] = values.get(name, 0.0) + value
        if name == "vllm:num_requests_waiting_by_reason":
            if 'reason="deferred"' in (labels or ""):
                deferred += value
            elif 'reason="capacity"' in (labels or ""):
                capacity += value
    values["bench:waiting_deferred"] = deferred
    values["bench:waiting_capacity"] = capacity
    return values


def synthetic_prompt(request_number: int, approximate_tokens: int, nonce: str) -> str:
    """Create a unique prompt of roughly the requested token count.

    Four characters/token is only an estimate. The server-reported usage is the
    authoritative prompt size printed in the final table.
    """
    target_chars = max(1, approximate_tokens) * 4
    prefix = (
        f"Unique continuous-batching load request {request_number}; nonce={nonce}. "
        "Read the following synthetic engineering event stream, then summarize "
        "its recurring failure patterns in concise bullet points.\n"
    )
    pieces: list[str] = [prefix]
    i = 0
    length = len(prefix)
    while length < target_chars:
        piece = (
            f"agent{request_number}-event{i}: component-{(i * 17 + request_number) % 997} "
            f"observed state-{(i * 31 + 7) % 4093}; "
        )
        pieces.append(piece)
        length += len(piece)
        i += 1
    return "".join(pieces)


def stream_chat(
    *,
    name: str,
    url: str,
    model: str,
    prompt: str,
    max_tokens: int,
    api_key: str | None,
    benchmark_start: float,
    first_token_event: threading.Event | None = None,
    timeout: float = 1800.0,
    temperature: float = 0,
    enable_thinking: bool = False,
) -> RequestResult:
    body = json.dumps(
        {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": temperature,
            "top_p": 1,
            "max_tokens": max_tokens,
            "stream": True,
            "stream_options": {"include_usage": True},
            "chat_template_kwargs": {"enable_thinking": enable_thinking},
        }
    ).encode()
    started_at = time.perf_counter()
    first_at: float | None = None
    usage: dict[str, Any] = {}
    finish_reason: str | None = None
    status: int | None = None

    try:
        with request(
            url,
            "/v1/chat/completions",
            data=body,
            api_key=api_key,
            timeout=timeout,
        ) as response:
            status = response.status
            buffer = b""
            while True:
                chunk = response.read1(4096)
                if not chunk:
                    break
                buffer += chunk
                while b"\n" in buffer:
                    line, buffer = buffer.split(b"\n", 1)
                    line = line.strip()
                    if not line.startswith(b"data:"):
                        continue
                    payload = line[5:].strip()
                    if not payload or payload == b"[DONE]":
                        continue
                    try:
                        event = json.loads(payload)
                    except json.JSONDecodeError:
                        continue
                    if event.get("usage"):
                        usage = event["usage"]
                    choices = event.get("choices") or []
                    if not choices:
                        continue
                    delta = choices[0].get("delta") or {}
                    token_text = (
                        delta.get("content")
                        or delta.get("reasoning")
                        or delta.get("reasoning_content")
                    )
                    if token_text and first_at is None:
                        first_at = time.perf_counter()
                        if first_token_event is not None:
                            first_token_event.set()
                    if choices[0].get("finish_reason"):
                        finish_reason = choices[0]["finish_reason"]
    except Exception as exc:  # Preserve results from the other concurrent calls.
        ended_at = time.perf_counter()
        if first_token_event is not None:
            first_token_event.set()
        return RequestResult(
            name=name,
            ok=False,
            status=getattr(exc, "code", status),
            started_s=started_at - benchmark_start,
            ttft_s=None if first_at is None else first_at - started_at,
            wall_s=ended_at - started_at,
            decode_s=None if first_at is None else ended_at - first_at,
            prompt_tokens=0,
            completion_tokens=0,
            effective_prefill_tok_s=None,
            decode_tok_s=None,
            delivered_completion_tok_s=None,
            finish_reason=finish_reason,
            error=f"{type(exc).__name__}: {exc}",
        )

    ended_at = time.perf_counter()
    prompt_tokens = int(usage.get("prompt_tokens") or 0)
    completion_tokens = int(usage.get("completion_tokens") or 0)
    decode_s = None if first_at is None else ended_at - first_at
    ttft_s = None if first_at is None else first_at - started_at
    decode_tok_s = None
    if decode_s and completion_tokens > 1:
        decode_tok_s = (completion_tokens - 1) / decode_s
    effective_prefill_tok_s = None
    if ttft_s and prompt_tokens:
        effective_prefill_tok_s = prompt_tokens / ttft_s
    delivered_completion_tok_s = (
        completion_tokens / (ended_at - started_at) if completion_tokens else None
    )
    return RequestResult(
        name=name,
        ok=status == 200,
        status=status,
        started_s=started_at - benchmark_start,
        ttft_s=ttft_s,
        wall_s=ended_at - started_at,
        decode_s=decode_s,
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        effective_prefill_tok_s=effective_prefill_tok_s,
        decode_tok_s=decode_tok_s,
        delivered_completion_tok_s=delivered_completion_tok_s,
        finish_reason=finish_reason,
    )


def value(snapshot: dict[str, float], metric: str) -> float:
    return snapshot.get(metric, 0.0)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Measure mixed prefill/decode behavior under concurrent load."
    )
    parser.add_argument("--url", default="http://ai.taildeab2.ts.net")
    parser.add_argument("--model", default="GLM-5.3-Flash-EXL3")
    parser.add_argument("--load-requests", type=int, default=2)
    parser.add_argument(
        "--prompt-tokens",
        type=int,
        default=30_000,
        help="Approximate tokens in each injected prompt (default: 30000)",
    )
    parser.add_argument("--anchor-output-tokens", type=int, default=1200)
    parser.add_argument("--load-output-tokens", type=int, default=200)
    parser.add_argument(
        "--inject-delay",
        type=float,
        default=1.0,
        help="Seconds after the anchor's first token before injecting load",
    )
    parser.add_argument("--interval", type=float, default=1.0)
    parser.add_argument("--timeout", type=float, default=1800.0)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    if args.load_requests < 1 or args.prompt_tokens < 1:
        parser.error("--load-requests and --prompt-tokens must be positive")

    api_key = os.environ.get("OPENAI_API_KEY") or os.environ.get("VLLM_API_KEY")
    with request(args.url, "/health", api_key=api_key, timeout=10.0) as response:
        if response.status != 200:
            raise RuntimeError(f"health returned HTTP {response.status}")

    benchmark_start = time.perf_counter()
    anchor_first_token = threading.Event()
    stop_monitor = threading.Event()
    samples: list[dict[str, float]] = []
    sample_lock = threading.Lock()

    def monitor() -> None:
        previous = metric_snapshot(args.url, api_key)
        previous_at = time.perf_counter()
        print(
            " elapsed  run wait  cap defer    KV%   prompt/s      gen/s  "
            "prompt_delta gen_delta",
            flush=True,
        )
        while True:
            stopping = stop_monitor.wait(args.interval)
            now = time.perf_counter()
            try:
                current = metric_snapshot(args.url, api_key)
            except Exception as exc:
                print(f"[metrics] {type(exc).__name__}: {exc}", file=sys.stderr)
                if stopping:
                    break
                continue
            elapsed = max(now - previous_at, 1e-9)
            prompt_delta = value(current, "vllm:prompt_tokens_total") - value(
                previous, "vllm:prompt_tokens_total"
            )
            generation_delta = value(current, "vllm:generation_tokens_total") - value(
                previous, "vllm:generation_tokens_total"
            )
            row = {
                "elapsed_s": now - benchmark_start,
                "running": value(current, "vllm:num_requests_running"),
                "waiting": value(current, "vllm:num_requests_waiting"),
                "waiting_capacity": value(current, "bench:waiting_capacity"),
                "waiting_deferred": value(current, "bench:waiting_deferred"),
                "kv_pct": 100 * value(current, "vllm:kv_cache_usage_perc"),
                "prompt_delta": prompt_delta,
                "generation_delta": generation_delta,
                "prompt_tok_s": prompt_delta / elapsed,
                "generation_tok_s": generation_delta / elapsed,
            }
            with sample_lock:
                samples.append(row)
            print(
                f"{row['elapsed_s']:8.1f} {row['running']:4.0f} {row['waiting']:4.0f} "
                f"{row['waiting_capacity']:4.0f} {row['waiting_deferred']:5.0f} "
                f"{row['kv_pct']:6.1f} {row['prompt_tok_s']:10.1f} "
                f"{row['generation_tok_s']:10.1f} {prompt_delta:12.0f} "
                f"{generation_delta:9.0f}",
                flush=True,
            )
            previous, previous_at = current, now
            if stopping:
                break

    monitor_thread = threading.Thread(target=monitor, name="metrics", daemon=True)
    monitor_thread.start()

    nonce = uuid.uuid4().hex
    anchor_prompt = (
        "Count upward from 1 using decimal integers separated by one space. "
        "Continue without commentary until the output limit is reached."
    )
    results: list[RequestResult] = []
    with concurrent.futures.ThreadPoolExecutor(
        max_workers=args.load_requests + 1
    ) as executor:
        futures = [
            executor.submit(
                stream_chat,
                name="anchor-decode",
                url=args.url,
                model=args.model,
                prompt=anchor_prompt,
                max_tokens=args.anchor_output_tokens,
                api_key=api_key,
                benchmark_start=benchmark_start,
                first_token_event=anchor_first_token,
                timeout=args.timeout,
            )
        ]
        if not anchor_first_token.wait(min(args.timeout, 300.0)):
            stop_monitor.set()
            raise RuntimeError("anchor did not produce a first token within 300 seconds")
        time.sleep(max(0.0, args.inject_delay))
        print(f"[inject] submitting {args.load_requests} large prompts", flush=True)
        for index in range(args.load_requests):
            futures.append(
                executor.submit(
                    stream_chat,
                    name=f"load-{index + 1}",
                    url=args.url,
                    model=args.model,
                    prompt=synthetic_prompt(index + 1, args.prompt_tokens, nonce),
                    max_tokens=args.load_output_tokens,
                    api_key=api_key,
                    benchmark_start=benchmark_start,
                    timeout=args.timeout,
                )
            )
        for future in concurrent.futures.as_completed(futures):
            result = future.result()
            results.append(result)
            prefill = (
                "n/a"
                if result.effective_prefill_tok_s is None
                else f"{result.effective_prefill_tok_s:.1f} tok/s"
            )
            decode = (
                "n/a" if result.decode_tok_s is None else f"{result.decode_tok_s:.1f} tok/s"
            )
            delivered = (
                "n/a"
                if result.delivered_completion_tok_s is None
                else f"{result.delivered_completion_tok_s:.1f} tok/s"
            )
            print(
                f"[done] {result.name}: ok={result.ok} wall={result.wall_s:.1f}s "
                f"ttft={result.ttft_s!s} prompt={result.prompt_tokens} "
                f"completion={result.completion_tokens} effective-prefill={prefill} "
                f"decode={decode} delivered={delivered}",
                flush=True,
            )

    benchmark_end = time.perf_counter()
    stop_monitor.set()
    monitor_thread.join(timeout=args.interval + 10)
    with sample_lock:
        observed = list(samples)
    mixed = [
        row
        for row in observed
        if row["prompt_delta"] > 0 and row["generation_delta"] > 0
    ]
    benchmark_wall_s = benchmark_end - benchmark_start
    total_prompt_tokens = sum(result.prompt_tokens for result in results)
    total_completion_tokens = sum(result.completion_tokens for result in results)
    metrics_prompt_tokens = sum(max(0.0, row["prompt_delta"]) for row in observed)
    metrics_generation_tokens = sum(
        max(0.0, row["generation_delta"]) for row in observed
    )
    summary = {
        "continuous_batching_observed": bool(mixed),
        "mixed_intervals": len(mixed),
        "benchmark_wall_s": benchmark_wall_s,
        "total_prompt_tokens": total_prompt_tokens,
        "total_completion_tokens": total_completion_tokens,
        "total_tokens": total_prompt_tokens + total_completion_tokens,
        "aggregate_prompt_tokens_per_wall_s": total_prompt_tokens / benchmark_wall_s,
        "aggregate_completion_tokens_per_wall_s": (
            total_completion_tokens / benchmark_wall_s
        ),
        "aggregate_total_tokens_per_wall_s": (
            (total_prompt_tokens + total_completion_tokens) / benchmark_wall_s
        ),
        "metrics_observed_prompt_tokens": metrics_prompt_tokens,
        "metrics_observed_generation_tokens": metrics_generation_tokens,
        "metrics_observed_total_tokens": metrics_prompt_tokens + metrics_generation_tokens,
        "max_running": max((row["running"] for row in observed), default=0),
        "max_waiting": max((row["waiting"] for row in observed), default=0),
        "max_waiting_capacity": max(
            (row["waiting_capacity"] for row in observed), default=0
        ),
        "max_waiting_deferred": max(
            (row["waiting_deferred"] for row in observed), default=0
        ),
        "peak_kv_pct": max((row["kv_pct"] for row in observed), default=0),
        "peak_prompt_tok_s": max(
            (row["prompt_tok_s"] for row in observed), default=0
        ),
        "peak_generation_tok_s": max(
            (row["generation_tok_s"] for row in observed), default=0
        ),
    }
    report = {
        "url": args.url,
        "model": args.model,
        "configuration": vars(args) | {"output": str(args.output) if args.output else None},
        "summary": summary,
        "requests": [asdict(result) for result in sorted(results, key=lambda r: r.name)],
        "samples": observed,
    }
    print("\nSummary:")
    print(json.dumps(summary, indent=2))
    if args.output:
        args.output.write_text(json.dumps(report, indent=2) + "\n")
        print(f"Full report: {args.output}")

    return 0 if summary["continuous_batching_observed"] and all(r.ok for r in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
