apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - garage-nodeport.yaml
  - garage-ts-funnel.yaml
  - garage-lb.yaml
  - openbao-lb.yaml
  - postgres-ts.yaml
  - postgres-lb.yaml
  - kubevirt-manager-lb.yaml