apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
spec:
  source:
    helm:
      values: |
        global:
          multiCluster:
            clusterName: cluster-a
          network: network1
