apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
spec:
  sources:
    - {} # This is a placeholder for the first source (Helm chart)
    - kustomize:
        patches:
          - patch: |-
              apiVersion: secrets.hashicorp.com/v1beta1
              kind: VaultAuth
              metadata:
                name: operator-auth
              spec:
                mount: kubernetes_cluster_mc
                kubernetes:
                  role: openbao-secrets-operator
            target:
              kind: VaultAuth
              name: operator-auth
