apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ALL_APPLICATIONS # This will be patched by Kustomize to target all applications
spec:
  source:
    kustomize:
      patches:
        - patch: |-
            apiVersion: secrets.hashicorp.com/v1beta1
            kind: VaultAuth
            spec:
              mount: kubernetes_cluster_mc
              kubernetes:
                role: openbao-secrets-operator
          target:
            kind: VaultAuth