---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: mcp-allow-tailscale-only
spec:
  podSelector:
    matchLabels:
      app: mcp-kubernetes
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tailscale
      ports:
        - port: 8080
