---
apiVersion: v1
kind: Service
metadata:
  name: mcp-ts-placeholder
  labels:
    app: mcp-kubernetes
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http-sse
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: mcp-kubernetes
