apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dnsutils
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
      # apply configs
    - repoURL: https://github.com/projectinitiative/homelab.git
      targetRevision: HEAD
      # The 'path' points to the directory containing your kustomization.yaml
      path: apps/base/dnsutils/config
  destination:
    server: https://kubernetes.default.svc
    namespace: dnsutils # Ensure this namespace is created first!
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Ensure the dnsutils namespace is created if not already by a prior app
