apiVersion: v1
kind: Service
metadata:
  name: gdrive-ftps
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ftps-gdrive
  ports:
    - name: ftp-control
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftp-data-0
      protocol: TCP
      port: 21100
      targetPort: 21100
    - name: ftp-data-1
      protocol: TCP
      port: 21101
      targetPort: 21101
    - name: ftp-data-2
      protocol: TCP
      port: 21102
      targetPort: 21102
