apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm-crds # This will be overridden by the overlay
spec:
  project: default
  source:
    repoURL: https://github.com/operator-framework/operator-lifecycle-manager.git
    targetRevision: v0.32.0 # Pinned from your file
    path: deploy/chart/crds
  destination:
    server: https://kubernetes.default.svc # This will be overridden
    namespace: operator-lifecycle-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace:false
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
