apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dnsutils-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      app: dnsutils
  template:
    metadata:
      labels:
        app: dnsutils
    spec:
      containers:
      - name: dnsutils
        image: ghcr.io/projectinitiative/dnsutils:latest
        # image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
        command:
          - sleep
          - "infinity"
        imagePullPolicy: Always
      restartPolicy: Always
