apiVersion: v1
kind: Service
metadata:
  name: dnsutils-nodeport
  namespace: dnsutils
spec:
  type: NodePort
  selector:
    app: dnsutils
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5201
      name: iperf3
