name: Build and Push openbao with TPM deps Container

# This section defines the trigger for the workflow.
on:
  push:
    branches:
      - main # Or your default branch
    # The 'paths' filter ensures this workflow only runs when one of
    # these specific files is changed in a push.
    paths:
      - '.github/workflows/build-push-openbao-hsm.yaml'
      - 'bootstrap/base/openbao/docker-openbao-hsm/Dockerfile'
      - 'bootstrap/base/openbao/docker-openbao-hsm/init-tools.nix'
      - 'bootstrap/base/openbao/docker-openbao-hsm/init-script.sh'
  
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # These permissions are required to push to the GitHub Container Registry.
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # The GITHUB_TOKEN is automatically created and provided by GitHub Actions.
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate lowercase repository owner name
        id: repo_owner
        run: echo "name=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: bootstrap/base/openbao/docker-openbao-hsm
          push: true
          tags: ghcr.io/${{ steps.repo_owner.outputs.name }}/openbao-hsm:latest

      - name: Clean up old containers 
        uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: user # or org
          token: ${{ secrets.GHCR_CLEANER }}
          repository-owner: ${{ github.repository_owner }}
          repository-name: ${{ github.repository }}
          delete-untagged: false
          keep-at-most: 8
